# Generated by Django 4.2.2 on 2023-08-11 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dependencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'ordering': ['-nombre'],
            },
        ),
        migrations.CreateModel(
            name='Inventor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('tipo', models.CharField(choices=[('E', 'Empleado'), ('A', 'Alumno')], default='E', max_length=8)),
                ('numero', models.IntegerField(default=0, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('dependencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencia', to='inventores.dependencias')),
            ],
            options={
                'ordering': ['-nombre', '-dependencia'],
            },
        ),
        migrations.CreateModel(
            name='Telefono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.EmailField(max_length=100)),
                ('inventor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventores.inventor')),
            ],
        ),
        migrations.CreateModel(
            name='Correo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.EmailField(max_length=100)),
                ('inventor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventores.inventor')),
            ],
        ),
        migrations.AddIndex(
            model_name='inventor',
            index=models.Index(fields=['nombre', 'tipo'], name='inventores__nombre_4feeff_idx'),
        ),
    ]
