# Generated by Django 4.2.2 on 2023-08-11 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventores', '0002_alter_telefono_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telefono',
            name='telefono',
            field=models.IntegerField(),
        ),
    ]
