# Generated by Django 4.2.2 on 2023-08-14 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0008_alter_requisito_tipo'),
        ('inventores', '0003_alter_telefono_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventor',
            name='registros',
            field=models.ManyToManyField(blank=True, to='registros.registro'),
        ),
    ]
