# Generated by Django 4.2.2 on 2023-08-14 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventores', '0004_inventor_registros'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventor',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='inventor',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
