# Generated by Django 4.2.2 on 2023-08-14 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventores', '0005_alter_inventor_nombre_alter_inventor_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='dependencias',
            name='abreviacion',
            field=models.CharField(default='CIETT', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
