# Generated by Django 4.2.2 on 2023-08-15 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventores', '0006_dependencias_abreviacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventor',
            name='sexo',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
