# Generated by Django 4.2.2 on 2023-07-13 20:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_institucional', models.EmailField(max_length=254, null=True)),
                ('titulo', models.CharField(max_length=500, null=True)),
                ('nombre', models.CharField(max_length=200, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('telefono', models.CharField(max_length=50, null=True)),
                ('contacto', models.CharField(max_length=200, null=True)),
                ('email_adicional', models.EmailField(max_length=254, null=True)),
                ('divulgacion', models.BooleanField(default=False)),
                ('divulgacion_info', models.CharField(max_length=200)),
                ('divulgacion_fecha_1', models.DateField(default=django.utils.timezone.now, null=True)),
                ('divulgacion_fecha_2', models.DateField(default=django.utils.timezone.now, null=True)),
                ('divulgacion_fecha_3', models.DateField(default=django.utils.timezone.now, null=True)),
                ('divulgacion_evidencia', models.URLField(null=True)),
                ('keywords', models.CharField(max_length=500, null=True)),
                ('area_aplicacion', models.CharField(max_length=100, null=True)),
                ('tipo_invencion', models.CharField(max_length=100, null=True)),
                ('descripcion', models.CharField(max_length=500, null=True)),
                ('problematica', models.CharField(max_length=500, null=True)),
                ('relevantes', models.CharField(max_length=500, null=True)),
                ('ocurrencia', models.CharField(max_length=500, null=True)),
                ('obvia', models.CharField(max_length=200, null=True)),
                ('financiamiento', models.CharField(max_length=100, null=True)),
                ('financiamiento_especifique', models.CharField(max_length=100, null=True)),
                ('invencion_involucramiento', models.BooleanField(default=False, null=True)),
                ('involucrameinto', models.CharField(max_length=200, null=True)),
                ('convenios', models.BooleanField(default=False, null=True)),
                ('convenios_tipo', models.CharField(max_length=200, null=True)),
                ('necesidad', models.CharField(max_length=50, null=True)),
                ('mercado', models.BooleanField(default=False)),
                ('mercado_especifique', models.CharField(max_length=200, null=True)),
                ('interes', models.BooleanField(default=False, null=True)),
                ('interes_especifique', models.CharField(max_length=200, null=True)),
                ('discovery', models.BooleanField(default=False, null=True)),
                ('discovery_especifique', models.CharField(max_length=200, null=True)),
                ('informacion_tecnica', models.URLField(null=True)),
                ('compromiso', models.BooleanField(default=True, null=True)),
                ('contacto_empresa', models.BooleanField(default=False, null=True)),
                ('contacto_especifique', models.CharField(max_length=500, null=True)),
            ],
            options={
                'ordering': ['nombre', 'titulo'],
            },
        ),
    ]
