# Generated by Django 4.2.2 on 2023-06-27 20:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_institucional', models.EmailField(max_length=254)),
                ('titulo', models.CharField(max_length=500)),
                ('nombre', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=50)),
                ('contacto', models.CharField(max_length=200)),
                ('email_adicional', models.EmailField(max_length=254)),
                ('divulgacion', models.BooleanField(default=False)),
                ('divulgacion_info', models.CharField(max_length=200)),
                ('divulgacion_fecha_1', models.DateField(blank=True, default=datetime.datetime(2023, 6, 27, 20, 38, 51, 275352))),
                ('divulgacion_fecha_2', models.DateField(blank=True, default=datetime.datetime(2023, 6, 27, 20, 38, 51, 275362))),
                ('divulgacion_fecha_3', models.DateField(blank=True, default=datetime.datetime(2023, 6, 27, 20, 38, 51, 275367))),
                ('divulgacion_evidencia', models.URLField(blank=True)),
                ('keywords', models.CharField(max_length=500)),
                ('area_aplicacion', models.CharField(max_length=100)),
                ('tipo_invencion', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=500)),
                ('problematica', models.CharField(max_length=500)),
                ('relevantes', models.CharField(max_length=500)),
                ('ocurrencia', models.CharField(max_length=500)),
                ('obvia', models.CharField(max_length=200)),
                ('financiamiento', models.CharField(max_length=100)),
                ('financiamiento_especifique', models.CharField(max_length=100)),
                ('invencion_involucramiento', models.BooleanField(default=False)),
                ('involucrameinto', models.CharField(max_length=200)),
                ('convenios', models.BooleanField(default=False)),
                ('convenios_tipo', models.CharField(max_length=200)),
                ('necesidad', models.CharField(max_length=50)),
                ('mercado', models.BooleanField(default=False)),
                ('mercado_especifique', models.CharField(max_length=200)),
                ('interes', models.BooleanField(default=False)),
                ('interes_especifique', models.CharField(max_length=200)),
                ('discovery', models.BooleanField(default=False)),
                ('discovery_especifique', models.CharField(max_length=200)),
                ('informacion_tecnica', models.URLField()),
                ('compromiso', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nombre', 'titulo'],
            },
        ),
    ]
