# Generated by Django 4.2.2 on 2023-06-27 20:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('creaFormulario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario',
            name='divulgacion_fecha_1',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='divulgacion_fecha_2',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='divulgacion_fecha_3',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
