# Generated by Django 4.2.2 on 2023-07-14 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creaFormulario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulario',
            name='dependencia',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
