# Generated by Django 4.2.2 on 2023-07-14 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creaFormulario', '0002_formulario_dependencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario',
            name='divulgacion_info',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
