# Generated by Django 4.2.2 on 2023-07-18 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creaFormulario', '0003_alter_formulario_divulgacion_info'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formulario',
            options={'ordering': ['id', 'nombre', 'titulo']},
        ),
    ]
