# Generated by Django 4.2.2 on 2023-07-20 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creaFormulario', '0005_alter_formulario_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulario',
            name='ingresado',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
