# Generated by Django 4.2.2 on 2023-08-07 19:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(default='MX/x/yyyy/000000', max_length=20, unique=True)),
                ('slug', models.SlugField(max_length=20, null=True, unique=True)),
                ('titulo', models.CharField(default='', max_length=500)),
                ('solicitante', models.CharField(default='Universidad Autónoma de Nuevo León', max_length=200)),
                ('fecha_presentacion', models.DateField(default=django.utils.timezone.now)),
                ('apoderado', models.CharField(default='LNGP', max_length=10)),
                ('rgp', models.CharField(default='DDAJ-000163/2023', max_length=20)),
                ('figura', models.CharField(default='Patente', max_length=15)),
                ('resolucion', models.CharField(choices=[('T', 'EN TRÁMITE'), ('A', 'ABANDONADA'), ('D', 'DESISTIDA'), ('N', 'NEGADA'), ('O', 'OTORGADA')], default='T', max_length=1)),
                ('resolucion_folio', models.IntegerField(blank=True)),
                ('resolucion_fecha', models.DateField(blank=True)),
            ],
            options={
                'ordering': ['-folio', '-fecha_presentacion'],
            },
        ),
        migrations.CreateModel(
            name='Titulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('expedido', models.DateField()),
                ('notificado', models.DateField()),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='titulo_no', to='registros.registro')),
            ],
        ),
        migrations.CreateModel(
            name='Requisito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('FORMA1', '1er. Requisito del Examen de Forma'), ('FORMA2', '2do. Requisito del Examen de Forma'), ('FORMAS', 'SATISFECHO'), ('FONDO1', '1er. Requisito del Examen de Forma'), ('FONDO2', '2do. Requisito del Examen de Forma'), ('FONDO3', '3er. Requisito del Examen de Forma'), ('FONDO4', '4to. Requisito del Examen de Forma')], default='FORMA1', max_length=34)),
                ('folio', models.IntegerField()),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisito', to='registros.registro')),
            ],
        ),
        migrations.AddIndex(
            model_name='registro',
            index=models.Index(fields=['figura'], name='registros_r_figura_9d9429_idx'),
        ),
    ]
