# Generated by Django 4.2.2 on 2023-07-20 18:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(default='MX/x/yyyy/000000', max_length=20, unique=True)),
                ('slug', models.SlugField(max_length=20, unique=True)),
                ('titulo', models.CharField(default='', max_length=500)),
                ('solicitante', models.CharField(default='Universidad Autónoma de Nuevo León', max_length=200)),
                ('fecha_presentacion', models.DateField(default=django.utils.timezone.now)),
                ('apoderado', models.CharField(default='LNGP', max_length=10)),
                ('rgp', models.CharField(default='DDAJ-000163/2023', max_length=20)),
                ('figura', models.CharField(default='Patente', max_length=15)),
                ('forma', models.CharField(blank=True, max_length=12, null=True)),
                ('forma_folio', models.IntegerField(blank=True, null=True)),
                ('forma_fecha', models.DateField(blank=True, null=True)),
                ('resolucion', models.CharField(choices=[('T', 'EN TRÁMITE'), ('A', 'ABANDONADA'), ('D', 'DESISTIDA'), ('N', 'NEGADA'), ('O', 'OTORGADA')], default='T', max_length=1)),
            ],
            options={
                'ordering': ['-folio', '-fecha_presentacion'],
            },
        ),
        migrations.CreateModel(
            name='Titulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('expedido', models.DateField()),
                ('notificado', models.DateField()),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='titulo_no', to='registros.registro')),
            ],
        ),
        migrations.CreateModel(
            name='Requisito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=20)),
                ('folio', models.IntegerField()),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisito', to='registros.registro')),
            ],
        ),
        migrations.AddIndex(
            model_name='registro',
            index=models.Index(fields=['figura'], name='registros_r_figura_9d9429_idx'),
        ),
    ]
