# Generated by Django 4.2.2 on 2023-08-07 19:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contestacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.IntegerField()),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('folio_contestacion', models.CharField(default='MX/E/2023/000000', max_length=20)),
                ('requisito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contestacion', to='registros.requisito')),
            ],
        ),
    ]
