# Generated by Django 4.2.2 on 2023-08-07 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0002_contestacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contestacion',
            name='folio_contestacion',
        ),
        migrations.AlterField(
            model_name='contestacion',
            name='folio',
            field=models.CharField(default='MX/E/2023/000000', max_length=20),
        ),
        migrations.AlterField(
            model_name='registro',
            name='resolucion_fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registro',
            name='resolucion_folio',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
