# Generated by Django 4.2.2 on 2023-08-08 14:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0003_remove_contestacion_folio_contestacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
