# Generated by Django 4.2.2 on 2023-08-08 15:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0004_registro_added'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registro',
            options={'ordering': ['-folio', '-fecha_presentacion', '-added']},
        ),
        migrations.AlterField(
            model_name='registro',
            name='folio',
            field=models.CharField(default='MX/x/yyyy/000000', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_folio', message='Formato del folio no válido', regex='^(MX/[afu]/\\[0-9]{4}/\\[0-9]{6})$')]),
        ),
    ]
