# Generated by Django 4.2.2 on 2023-08-08 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0006_alter_registro_folio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registro',
            name='resolucion',
        ),
        migrations.RemoveField(
            model_name='registro',
            name='resolucion_fecha',
        ),
        migrations.RemoveField(
            model_name='registro',
            name='resolucion_folio',
        ),
        migrations.CreateModel(
            name='Resolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolucion', models.CharField(choices=[('T', 'EN TRÁMITE'), ('A', 'ABANDONADA'), ('D', 'DESISTIDA'), ('N', 'NEGADA'), ('O', 'OTORGADA')], default='T', max_length=1)),
                ('folio', models.IntegerField(blank=True, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resolucion', to='registros.registro')),
            ],
        ),
    ]
