# Generated by Django 4.2.2 on 2023-08-09 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0007_remove_registro_resolucion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisito',
            name='tipo',
            field=models.CharField(choices=[('FORMA1', '1er. Requisito del Examen de Forma'), ('FORMA2', '2do. Requisito del Examen de Forma'), ('FORMAS', 'SATISFECHO'), ('FONDO1', '1er. Requisito del Examen de Fondo'), ('FONDO2', '2do. Requisito del Examen de Fondo'), ('FONDO3', '3er. Requisito del Examen de Fondo'), ('FONDO4', '4to. Requisito del Examen de Fondo')], default='FORMA1', max_length=34),
        ),
    ]
