# Generated by Django 4.2.2 on 2023-08-15 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0008_alter_requisito_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resolucion',
            name='resolucion',
            field=models.CharField(choices=[('A', 'ABANDONADA'), ('D', 'DESISTIDA'), ('N', 'NEGADA'), ('O', 'OTORGADA')], default='O', max_length=1),
        ),
    ]
